/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

#define CALC_PROG 0x31111111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(numbers *, CLIENT *);
extern  int * suma_1_svc(numbers *, struct svc_req *);
#define RESTA 2
extern  int * resta_1(numbers *, CLIENT *);
extern  int * resta_1_svc(numbers *, struct svc_req *);
#define MULTIPLICACION 3
extern  int * multiplicacion_1(numbers *, CLIENT *);
extern  int * multiplicacion_1_svc(numbers *, struct svc_req *);
#define DIVISION 4
extern  float * division_1(numbers *, CLIENT *);
extern  float * division_1_svc(numbers *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define MULTIPLICACION 3
extern  int * multiplicacion_1();
extern  int * multiplicacion_1_svc();
#define DIVISION 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
