/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
suma_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = argp->a + argp->b;
    printf("%d + %d = %d\n",argp->a,argp->b,result);

	return &result;
}

int *
resta_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = argp->a - argp->b;
    printf("%d - %d = %d\n",argp->a,argp->b,result);

	return &result;
}

int *
multiplicacion_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = argp->a * argp->b;
    printf("%d * %d = %d\n",argp->a,argp->b,result);
	
	return &result;
}

float *
division_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->a / argp->b;
    printf("%d / %d = %f\n",argp->a,argp->b,result);

	return &result;
}
